server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: monge-api
  datasource:
    url: jdbc:h2:mem:intercampiDB
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  # sql:
  #   init:
  #     mode: always
  #     data-locations: classpath:bd/bolsista/*.sql,classpath:bd/orientador/*.sql
  
logging:
  level:
    br.ufpr.monge: INFO
    org.springframework.web: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

security:
  api-key: changeme123